SEED_VERSION = "6"

SERVICES = [
    {
        "slug": "ai-consulting",
        "title": "AI Consulting",
        "tagline": "Clarity before code.",
        "summary": "Independent, business-first advice on where AI genuinely creates value in your organisation — and where it doesn't.",
        "problem": "Most AI initiatives fail not because of the technology, but because they were never tied to a business problem worth solving. Boards feel pressure to 'do AI'; teams buy tools before defining outcomes.",
        "what_we_do": [
            "Assess your operations, data and workflows to find high-value AI opportunities",
            "Score each opportunity by business impact, feasibility and risk",
            "Design a pragmatic AI roadmap with clear owners, budgets and milestones",
            "Advise on build vs. buy, vendor selection and governance",
        ],
        "process": [
            {"step": "Discover", "desc": "Structured interviews and process mapping across functions to understand how your business actually runs."},
            {"step": "Assess", "desc": "Data readiness audit and opportunity scoring — impact, feasibility, cost and risk for every candidate use case."},
            {"step": "Recommend", "desc": "A prioritised roadmap with business cases, not a slide deck of buzzwords."},
            {"step": "Enable", "desc": "Pilot definition, vendor evaluation and governance frameworks so execution starts on solid ground."},
        ],
        "deliverables": ["AI opportunity assessment report", "Prioritised AI roadmap with business cases", "Data readiness audit", "Build vs. buy recommendations", "Governance and risk framework"],
        "tech_stack": ["OpenAI / Anthropic / Gemini", "Azure AI", "AWS Bedrock", "LangChain", "Vector databases", "MLOps tooling"],
        "faqs": [
            {"q": "Do we need clean data before engaging you?", "a": "No. Assessing data readiness is part of the engagement. We tell you exactly what is usable today and what needs work."},
            {"q": "Are you tied to specific AI vendors?", "a": "We are vendor-neutral. Recommendations are driven by your context, budget and constraints — not partnership commissions."},
        ],
    },
    {
        "slug": "ai-transformation",
        "title": "AI Transformation",
        "tagline": "From pilot to production.",
        "summary": "End-to-end delivery of AI systems that move from proof-of-concept into daily business operations — measured, governed and adopted.",
        "problem": "The industry is littered with pilots that never shipped. Moving AI into production requires engineering discipline, change management and measurement — not just a model.",
        "what_we_do": [
            "Build production-grade AI systems: copilots, document intelligence, forecasting, agents",
            "Integrate AI into existing workflows, ERPs and CRMs rather than bolting on new tools",
            "Establish evaluation, monitoring and human-in-the-loop guardrails",
            "Train teams and manage adoption so the system is actually used",
        ],
        "process": [
            {"step": "Frame", "desc": "Define the workflow, the metric it must move, and the guardrails it must respect."},
            {"step": "Prototype", "desc": "A working prototype on your real data within weeks — evaluated against agreed success criteria."},
            {"step": "Industrialise", "desc": "Production engineering: security, latency, cost controls, monitoring, fallback behaviour."},
            {"step": "Adopt", "desc": "Training, rollout, and measurement. Value is only real when the team uses it daily."},
        ],
        "deliverables": ["Production AI application", "Evaluation and monitoring suite", "Integration with existing systems", "Team training and playbooks", "Cost and performance dashboards"],
        "tech_stack": ["LLM APIs (GPT, Claude, Gemini)", "RAG pipelines", "Python / FastAPI", "Vector search", "Kubernetes", "Observability tooling"],
        "faqs": [
            {"q": "How long until we see something working?", "a": "Typically 3–6 weeks to a working prototype on your data, depending on data access and complexity."},
            {"q": "How do you handle data privacy?", "a": "We design for your compliance context — private deployments, data residency, redaction and audit trails where required."},
        ],
    },
    {
        "slug": "digital-transformation",
        "title": "Digital Transformation",
        "tagline": "Modernise what matters.",
        "summary": "Replacing manual processes and legacy systems with modern digital operations — sequenced by business value, not by technology fashion.",
        "problem": "Transformation programmes fail when they try to change everything at once. The result: budget overruns, change fatigue, and systems nobody adopted.",
        "what_we_do": [
            "Map current processes and identify the highest-friction, highest-value areas first",
            "Modernise legacy systems incrementally with minimal business disruption",
            "Digitise paper and spreadsheet workflows into auditable systems",
            "Build the internal capability to sustain change after we leave",
        ],
        "process": [
            {"step": "Baseline", "desc": "Process mapping and cost-of-current-state analysis. You can't improve what you haven't measured."},
            {"step": "Sequence", "desc": "A phased roadmap ordered by ROI and risk — quick wins fund the deeper work."},
            {"step": "Deliver", "desc": "Iterative delivery in 2–4 week increments with working software at every step."},
            {"step": "Embed", "desc": "Training, documentation and handover so improvements survive beyond the engagement."},
        ],
        "deliverables": ["Current-state assessment", "Phased transformation roadmap", "Modernised systems and workflows", "Change management support", "Capability handover"],
        "tech_stack": ["React / Node / Python", "PostgreSQL / MongoDB", "Cloud platforms (AWS, Azure, GCP)", "API-first integration", "Low-code where appropriate"],
        "faqs": [
            {"q": "Can you work alongside our existing IT team?", "a": "Yes — most engagements are collaborative. We augment your team and transfer knowledge deliberately."},
            {"q": "What if we've had a failed transformation before?", "a": "Common, and usually a sequencing problem. We start with a smaller scope that proves value fast and rebuilds trust."},
        ],
    },
    {
        "slug": "custom-software-development",
        "title": "Custom Software Development",
        "tagline": "Software shaped to your business.",
        "summary": "Bespoke systems built when off-the-shelf tools can't model how your business actually works.",
        "problem": "Generic SaaS forces your operations into someone else's assumptions. Workarounds multiply, data fragments, and the tool becomes the bottleneck.",
        "what_we_do": [
            "Design and build custom platforms, portals and internal tools",
            "Replace brittle spreadsheet-driven operations with real systems",
            "Integrate disconnected tools into a coherent architecture",
            "Own quality end-to-end: architecture, testing, security, deployment",
        ],
        "process": [
            {"step": "Specify", "desc": "Workshops to define the domain model, workflows and edge cases before a line of code."},
            {"step": "Architect", "desc": "A design that fits your scale and budget today with clean paths to grow."},
            {"step": "Build", "desc": "Agile delivery with demos every sprint and honest progress reporting."},
            {"step": "Operate", "desc": "Deployment, monitoring, SLAs and ongoing evolution as your business changes."},
        ],
        "deliverables": ["Production application", "Technical architecture documentation", "Automated test suite", "CI/CD pipeline", "Maintenance and support plan"],
        "tech_stack": ["React / TypeScript", "Python / FastAPI / Node.js", "PostgreSQL / MongoDB", "Docker / Kubernetes", "AWS / Azure / GCP"],
        "faqs": [
            {"q": "Who owns the code?", "a": "You do. Full IP transfer, documented codebases, no lock-in."},
            {"q": "How do you keep projects on budget?", "a": "Fixed-scope discovery first, then phased delivery with re-approval gates. No open-ended billing."},
        ],
    },
    {
        "slug": "web-applications",
        "title": "Web Applications",
        "tagline": "Fast, secure, built to scale.",
        "summary": "High-performance web platforms — customer portals, SaaS products, marketplaces and internal dashboards.",
        "problem": "Slow, insecure or unscalable web software silently costs revenue: abandoned carts, churned users, support overhead, security exposure.",
        "what_we_do": [
            "Build responsive, accessible web applications with modern frameworks",
            "Engineer for performance: sub-second loads, efficient APIs, smart caching",
            "Bake in security, monitoring and analytics from day one",
            "Design information architecture that scales with your product roadmap",
        ],
        "process": [
            {"step": "Define", "desc": "User journeys, data model and success metrics agreed before design."},
            {"step": "Design", "desc": "Wireframes to high-fidelity UI with your brand system."},
            {"step": "Engineer", "desc": "Component-driven development, automated testing, staged environments."},
            {"step": "Launch", "desc": "Performance hardening, SEO, analytics and a measured rollout."},
        ],
        "deliverables": ["Production web application", "Design system and component library", "API layer and documentation", "Analytics and monitoring setup", "SEO foundation"],
        "tech_stack": ["React / Next.js", "FastAPI / Node.js", "PostgreSQL / MongoDB / Redis", "Tailwind CSS", "Vercel / AWS"],
        "faqs": [
            {"q": "Can you take over an existing application?", "a": "Yes. We run a technical audit first, stabilise what's critical, then improve incrementally."},
            {"q": "Do you handle hosting and maintenance?", "a": "We can own the full lifecycle or hand over to your team with complete documentation — your choice."},
        ],
    },
    {
        "slug": "mobile-applications",
        "title": "Mobile Applications",
        "tagline": "Your business, in their pocket.",
        "summary": "iOS and Android applications for customers and field teams — native quality with pragmatic cross-platform engineering.",
        "problem": "A poor mobile experience is a daily reminder to churn. And building two native apps badly costs more than building one cross-platform app well.",
        "what_we_do": [
            "Build cross-platform apps with React Native / Flutter where it fits, native where it matters",
            "Design offline-first field and operations apps for real-world conditions",
            "Integrate payments, notifications, maps and device capabilities",
            "Manage store submission, releases and crash monitoring",
        ],
        "process": [
            {"step": "Scope", "desc": "Platform strategy, feature prioritisation, and an honest cross-platform vs. native recommendation."},
            {"step": "Prototype", "desc": "Clickable prototype validated with real users before full build."},
            {"step": "Build", "desc": "Sprint-based delivery with TestFlight / Play beta builds throughout."},
            {"step": "Ship", "desc": "Store approval, phased rollout, analytics and iteration."},
        ],
        "deliverables": ["Published iOS and Android apps", "Backend APIs and admin panel", "Push notification infrastructure", "Crash and analytics monitoring", "Release playbook"],
        "tech_stack": ["React Native / Flutter", "Swift / Kotlin (native modules)", "Firebase", "FastAPI backends", "App Store / Play Console"],
        "faqs": [
            {"q": "Cross-platform or native?", "a": "For most business apps, cross-platform delivers 90% of native quality at 60% of the cost. We'll tell you honestly if your case is the exception."},
            {"q": "Do you handle app store approval?", "a": "Yes — including compliance review, store assets and rejection handling."},
        ],
    },
    {
        "slug": "ui-ux-design",
        "title": "UI/UX Design",
        "tagline": "Design that earns trust.",
        "summary": "Research-driven product design — from user flows to polished interfaces and design systems your team can build on.",
        "problem": "Ugly software gets tolerated; confusing software gets abandoned. Poor UX shows up as support tickets, training costs and lost deals.",
        "what_we_do": [
            "Run user research and usability audits on existing products",
            "Design end-to-end flows, wireframes and high-fidelity interfaces",
            "Build token-driven design systems for consistency at scale",
            "Prototype and test before engineering spends a rupee",
        ],
        "process": [
            {"step": "Research", "desc": "User interviews, analytics review and heuristic evaluation."},
            {"step": "Structure", "desc": "Information architecture and user flows that remove friction."},
            {"step": "Design", "desc": "High-fidelity UI with your brand, tested with real users."},
            {"step": "Systemise", "desc": "A documented design system so quality survives handover."},
        ],
        "deliverables": ["UX audit report", "User flows and wireframes", "High-fidelity UI designs", "Interactive prototypes", "Design system and tokens"],
        "tech_stack": ["Figma", "Design tokens", "Framer prototyping", "Accessibility tooling (WCAG 2.1)", "Usability testing platforms"],
        "faqs": [
            {"q": "Can you redesign without breaking what users know?", "a": "Yes — evolutionary redesign is our default. We fix friction without discarding learned behaviour."},
            {"q": "Do you hand off to our developers?", "a": "We deliver developer-ready specs, tokens and a walkthrough. We can also pair with your team during build."},
        ],
    },
    {
        "slug": "cloud-solutions",
        "title": "Cloud Solutions",
        "tagline": "Infrastructure without drama.",
        "summary": "Cloud migration, architecture and cost optimisation on AWS, Azure and GCP — reliable, secure and financially disciplined.",
        "problem": "Cloud bills grow silently. Legacy servers create risk. And migrations done badly cause the outages they were meant to prevent.",
        "what_we_do": [
            "Plan and execute zero-downtime cloud migrations",
            "Design secure, scalable architectures sized to actual demand",
            "Cut cloud spend through rightsizing, reservations and architectural fixes",
            "Set up infrastructure-as-code, CI/CD and disaster recovery",
        ],
        "process": [
            {"step": "Audit", "desc": "Current infrastructure, dependencies, risk and cost baseline."},
            {"step": "Design", "desc": "Target architecture with security, compliance and cost modelling."},
            {"step": "Migrate", "desc": "Phased, rehearsed cutovers with rollback plans. No big-bang weekends."},
            {"step": "Optimise", "desc": "Continuous cost and performance tuning with monthly reporting."},
        ],
        "deliverables": ["Cloud architecture design", "Migration execution", "Infrastructure-as-code (Terraform)", "Cost optimisation report", "DR and backup strategy"],
        "tech_stack": ["AWS / Azure / GCP", "Terraform / Pulumi", "Kubernetes / Docker", "GitHub Actions / GitLab CI", "Datadog / Grafana"],
        "faqs": [
            {"q": "Can you reduce our existing cloud bill?", "a": "Industry benchmarks for unoptimised accounts commonly sit at 25–45%. We audit first and quantify your specific savings before you commit to anything."},
            {"q": "Which cloud should we choose?", "a": "The one that fits your workloads, team skills and existing contracts. We're certified across all three majors and have no resale incentive."},
        ],
    },
    {
        "slug": "data-analytics",
        "title": "Data Analytics",
        "tagline": "Decisions, not dashboards.",
        "summary": "Data pipelines, warehouses and analytics that turn scattered operational data into decisions leadership can act on.",
        "problem": "Most organisations are data-rich and insight-poor. Reports take days, numbers don't reconcile, and decisions default to gut feel.",
        "what_we_do": [
            "Consolidate scattered data sources into a governed warehouse",
            "Build automated reporting and self-serve dashboards",
            "Develop forecasting and anomaly detection models",
            "Establish data quality, definitions and ownership",
        ],
        "process": [
            {"step": "Map", "desc": "Inventory data sources, owners and the decisions each metric should drive."},
            {"step": "Pipeline", "desc": "Reliable ELT into a single warehouse with tested transformations."},
            {"step": "Model", "desc": "Metrics layer with agreed definitions — one version of the truth."},
            {"step": "Activate", "desc": "Dashboards, alerts and forecasts embedded into weekly operating rhythm."},
        ],
        "deliverables": ["Data warehouse and pipelines", "Metrics layer and documentation", "Executive and operational dashboards", "Forecasting models", "Data governance framework"],
        "tech_stack": ["BigQuery / Snowflake / ClickHouse", "dbt", "Airflow / Dagster", "Metabase / Power BI / Looker", "Python / SQL"],
        "faqs": [
            {"q": "Our data is a mess. Where do we start?", "a": "With the three decisions that matter most to leadership. We build backwards from those, not forwards from every table you own."},
            {"q": "How long to a first dashboard?", "a": "A trustworthy first dashboard on consolidated data typically lands in 4–6 weeks."},
        ],
    },
    {
        "slug": "automation",
        "title": "Automation",
        "tagline": "Remove the repetitive.",
        "summary": "Workflow and process automation that eliminates manual, error-prone work — from document processing to cross-system orchestration.",
        "problem": "Skilled people spend hours re-typing data between systems, chasing approvals and reconciling spreadsheets. That time has a cost — and a better use.",
        "what_we_do": [
            "Automate document-heavy workflows with intelligent extraction",
            "Orchestrate cross-system processes: approvals, onboarding, reconciliation",
            "Deploy RPA and API-based automation where each fits best",
            "Measure hours saved and error rates so ROI is visible",
        ],
        "process": [
            {"step": "Observe", "desc": "Shadow the actual process — not the documented one — to find real friction."},
            {"step": "Quantify", "desc": "Hours, error rates and cost per process. Automation targets ranked by payback."},
            {"step": "Automate", "desc": "Build with humans-in-the-loop for exceptions, not blind straight-through processing."},
            {"step": "Scale", "desc": "Extend to adjacent processes once the first automation proves its numbers."},
        ],
        "deliverables": ["Process automation implementation", "Exception handling workflows", "ROI measurement dashboard", "Runbooks and training", "Automation roadmap"],
        "tech_stack": ["Python", "n8n / Zapier / Make", "OCR + LLM extraction", "REST / webhook integration", "RPA platforms"],
        "faqs": [
            {"q": "Will automation replace our staff?", "a": "In our engagements it redirects them. The business case is usually capacity and accuracy, not headcount."},
            {"q": "What's a typical payback period?", "a": "Across the industry, well-chosen automations typically pay back in 3–9 months. We quantify the expected payback per process before building — and won't build ones that don't clear it."},
        ],
    },
    {
        "slug": "technology-consulting",
        "title": "Technology Consulting",
        "tagline": "A CTO's judgement, on demand.",
        "summary": "Independent technology strategy, architecture review and vendor guidance for leadership teams making high-stakes decisions.",
        "problem": "Technology decisions made without independent expertise become expensive to reverse: wrong platforms, bad contracts, unscalable architectures.",
        "what_we_do": [
            "Advise on technology strategy, budgets and team structure",
            "Review architectures and codebases before you buy, build or scale",
            "Support vendor selection, RFPs and contract negotiation",
            "Provide fractional CTO leadership for growing organisations",
        ],
        "process": [
            {"step": "Context", "desc": "Business goals, constraints and the decision on the table."},
            {"step": "Investigate", "desc": "Technical due diligence: systems, vendors, teams, contracts."},
            {"step": "Advise", "desc": "Clear, written recommendations with trade-offs made explicit."},
            {"step": "Support", "desc": "Ongoing counsel through execution — not advice and exit."},
        ],
        "deliverables": ["Technology strategy document", "Architecture / code audit report", "Vendor evaluation matrix", "Budget and roadmap review", "Fractional CTO engagement"],
        "tech_stack": ["Architecture review frameworks", "Cloud cost analysis", "Security posture assessment", "Due diligence tooling", "Engineering metrics"],
        "faqs": [
            {"q": "When does fractional CTO make sense?", "a": "When technology decisions outpace in-house expertise but a full-time CTO isn't justified yet — commonly ₹50L–₹5Cr technology budgets."},
            {"q": "Can you audit a vendor's proposal?", "a": "Yes — technical and commercial review of proposals, architectures and contracts is one of our most requested services."},
        ],
    },
]

INDUSTRIES = [
    {
        "slug": "healthcare",
        "name": "Healthcare",
        "headline": "Care delivery, minus the paperwork.",
        "overview": "Hospitals, clinics and health networks run on processes that were never designed for scale. We digitise patient journeys, automate administration and make clinical data usable — within compliance boundaries.",
        "challenges": ["Manual patient intake, records and claims processing", "Fragmented systems across departments and locations", "Compliance and data privacy obligations", "Staff time consumed by administration instead of care"],
        "solutions": ["Patient intake and appointment automation", "Claims triage and document intelligence", "Unified dashboards across facilities", "Secure, compliant data platforms"],
        "outcomes": ["Faster patient throughput", "Lower administrative cost per case", "Audit-ready compliance posture"],
        "related_case_study": "fitness-wellness-platform",
    },
    {
        "slug": "retail-ecommerce",
        "name": "Retail & E-commerce",
        "headline": "Every store, every SKU, one picture.",
        "overview": "Retail margins are won in inventory, pricing and customer experience. We build the data and automation backbone that lets retailers act on demand signals instead of reacting to stockouts.",
        "challenges": ["Stockouts and overstock from gut-feel forecasting", "Disconnected online and offline channels", "Margin erosion hidden in scattered data", "Manual reconciliation across POS, ERP and marketplaces"],
        "solutions": ["Demand forecasting and inventory intelligence", "Omnichannel data consolidation", "Pricing and promotion analytics", "Order and returns automation"],
        "outcomes": ["Fewer stockouts, leaner inventory", "Margin visibility by store and SKU", "Hours of reconciliation removed weekly"],
        "related_case_study": "business-process-automation",
    },
    {
        "slug": "education",
        "name": "Education",
        "headline": "Institutions built for modern learners.",
        "overview": "Universities, school groups and ed-tech ventures need digital platforms that serve students at scale — admissions to alumni — without an army of administrators.",
        "challenges": ["Paper-driven admissions and administration", "Poor visibility into student progress and risk", "Legacy portals students avoid using", "Faculty time lost to repetitive coordination"],
        "solutions": ["Digital learning and administration platforms", "Student analytics and early-warning systems", "Admissions and fee workflow automation", "Modern student-facing portals and apps"],
        "outcomes": ["Higher completion and engagement", "Faster admissions cycles", "Administration cost per student down"],
        "related_case_study": "elearning-skill-development",
    },
    {
        "slug": "financial-services",
        "related_case_study": "document-processing-automation",
        "name": "Financial Services",
        "headline": "Trust, speed and compliance — together.",
        "overview": "Lenders, insurers and fintechs compete on speed of decision and quality of risk. We build the data pipelines, automation and secure platforms that make both possible.",
        "challenges": ["Slow, manual underwriting and KYC processes", "Regulatory reporting consuming analyst time", "Legacy core systems limiting product launches", "Fraud and risk signals scattered across systems"],
        "solutions": ["Document intelligence for KYC and underwriting", "Automated regulatory reporting pipelines", "API layers over legacy cores", "Risk analytics and monitoring"],
        "outcomes": ["Decision times cut from days to hours", "Reporting produced automatically", "New products launched without core replacement"],
    },
    {
        "slug": "manufacturing-logistics",
        "name": "Manufacturing & Logistics",
        "headline": "The physical world, digitally visible.",
        "overview": "Plants, fleets and warehouses generate enormous operational data that rarely reaches decision-makers in time. We connect operations to systems that see problems before they become losses.",
        "challenges": ["No real-time visibility into production or fleet status", "Downtime discovered after the cost is incurred", "Manual planning across procurement, production and dispatch", "Ageing on-premise systems nearing end of life"],
        "solutions": ["Operations dashboards and alerting", "Predictive maintenance analytics", "Planning and dispatch automation", "Cloud migration of legacy systems"],
        "outcomes": ["Downtime caught earlier, cost avoided", "Planning cycles compressed", "Infrastructure cost reduced"],
        "related_case_study": "business-process-automation",
    },
    {
        "slug": "government-public-sector",
        "related_case_study": "crowd-headcount-monitoring",
        "name": "Government & Public Sector",
        "headline": "Citizen services that actually serve.",
        "overview": "Public institutions carry the highest bar for accessibility, transparency and scale. We build citizen-facing services and internal systems that meet it — pragmatically and accountably.",
        "challenges": ["Paper-based citizen services with long queues", "Data locked in departmental silos", "Procurement and compliance complexity", "Accessibility obligations often unmet"],
        "solutions": ["Digital citizen service portals", "Inter-department data platforms", "Workflow digitisation with audit trails", "WCAG-compliant accessible interfaces"],
        "outcomes": ["Service turnaround times reduced", "Full auditability of every request", "Accessible to every citizen"],
    },
]

CASE_STUDIES = [
    {
        "slug": "corporate-attendance-management",
        "title": "Corporate Attendance Management System",
        "client": "",
        "illustrative": False,
        "sector": "Corporate & Enterprise",
        "year": "",
        "teaser": "Attendance tracking, employee records and reporting brought into a single interface, so administrative teams spend less time on manual workforce operations.",
        "challenge": "Attendance in corporate and organizational environments is typically spread across manual registers, disconnected tools and ad-hoc spreadsheets. That fragmentation makes day-to-day tracking laborious, employee records harder to maintain, and reporting slow to produce — consuming administrative capacity that should be going elsewhere.",
        "approach": "We built the platform around the people who use it daily. Rather than adding another system for administrators to maintain, we consolidated attendance tracking, employee record management and reporting into one easy-to-use interface, and designed for accuracy and scale from the outset so the system stays dependable as headcount grows.",
        "solution": "A fully functional attendance management system for corporate and organizational environments. It simplifies attendance tracking, centralises employee record management, and produces the reporting administrators need — streamlining workforce operations and improving overall administrative efficiency.",
        "focus": ["Accuracy", "Scalability", "User experience"],
        "results": [],
        "technologies": [],
        "testimonial": None,
    },
    {
        "slug": "fitness-wellness-platform",
        "title": "Fitness & Wellness Platform",
        "client": "",
        "illustrative": False,
        "sector": "Health & Wellness",
        "year": "",
        "teaser": "A fitness management platform for tracking workouts, monitoring progress and staying accountable to health goals — seamless across devices.",
        "challenge": "People pursuing health goals rarely lack motivation — they lack one place to see whether what they are doing is working. Workout history, performance metrics and progress usually live across separate apps and notes, which makes consistency hard to sustain.",
        "approach": "We designed for daily use first: an intuitive experience for managing fitness activities, with performance metrics and progress presented clearly enough to act on. A modern, scalable architecture underpins it so the experience holds up across different devices.",
        "solution": "A comprehensive fitness management platform where users track workouts, monitor progress and maintain their health goals. Members manage fitness activities, view performance metrics and monitor overall progress in one place, delivered as a complete end-to-end product.",
        "focus": ["Usability", "Reliability", "Performance"],
        "results": [],
        "technologies": [],
        "testimonial": None,
    },
    {
        "slug": "crowd-headcount-monitoring",
        "title": "Crowd Headcount & Monitoring System",
        "client": "",
        "illustrative": False,
        "sector": "Government & Public Sector",
        "year": "",
        "teaser": "Crowd analytics for public spaces — counting and analysing people so authorities hold reliable situational awareness at large gatherings.",
        "challenge": "Public sector teams managing large gatherings and public events need dependable population estimates to make operational decisions. Manual estimation is slow and imprecise, which limits visibility at exactly the moments when situational awareness matters most.",
        "approach": "We built around the operational decision rather than the technology. The system had to produce counts and analysis that authorities can act on in real conditions, so accuracy and efficiency were treated as delivery requirements rather than aspirations, and the design was kept scalable across varied public-space deployments.",
        "solution": "A crowd analytics solution supporting public sector and government use cases in crowd monitoring and population estimation. It enables efficient counting and analysis of people in public spaces, improving visibility and situational awareness for managing large gatherings and public events.",
        "focus": ["Accuracy", "Efficiency", "Real-world applicability"],
        "results": [],
        "technologies": [],
        "testimonial": None,
    },
    {
        "slug": "community-networking-platform",
        "title": "Community Networking & Engagement Platform",
        "client": "",
        "illustrative": False,
        "sector": "Community & Engagement",
        "year": "",
        "teaser": "A centralised space for community members to share information, interact and collaborate — built for connectivity and long-term growth.",
        "challenge": "Communities lose momentum when information is scattered and members have no reliable place to find one another. Without a central space, sharing updates, managing member interactions and reaching shared resources all become harder than they should be.",
        "approach": "We treated accessibility as the design constraint: a user-friendly interface that members of varying comfort with technology can navigate, on a scalable architecture that supports the community as it grows rather than only as it stands today.",
        "solution": "A digital platform that strengthens community engagement and connectivity among members. It provides a centralised space for sharing information, managing member interactions and fostering collaboration, enabling seamless communication and efficient access to community resources.",
        "focus": ["Accessibility", "Engagement", "Long-term community growth"],
        "results": [],
        "technologies": [],
        "testimonial": None,
    },
    {
        "slug": "enterprise-hr-intelligence",
        "title": "Enterprise HR Intelligence Platform",
        "client": "",
        "illustrative": False,
        "sector": "Corporate & Enterprise",
        "year": "",
        "teaser": "A smart workforce platform that streamlines routine HR tasks and speeds up access to information through intelligent automation.",
        "challenge": "HR teams spend a disproportionate share of their time on routine, repeatable tasks and on answering questions whose answers already exist somewhere in the organisation. That workload slows decision-making and crowds out higher-value work.",
        "approach": "We focused on the tasks that repeat. Applying intelligent automation to routine processes and making information easier to reach reduces effort where it accumulates — while keeping the experience straightforward enough that teams actually adopt it.",
        "solution": "A smart workforce solution that enhances HR operations and employee management. It helps teams access information, streamlines routine tasks and improves operational efficiency through intelligent automation, supporting faster decision-making and improved productivity against modern workplace requirements.",
        "focus": ["Scalability", "Usability", "Business impact"],
        "results": [],
        "technologies": [],
        "testimonial": None,
    },
    {
        "slug": "productivity-knowledge-platform",
        "title": "Personal Productivity & Knowledge Management Platform",
        "client": "",
        "illustrative": False,
        "sector": "Productivity & Knowledge",
        "year": "",
        "teaser": "A structured workspace for capturing knowledge, tracking important content and keeping personal information organised and retrievable.",
        "challenge": "Ideas and useful information accumulate faster than most people can organise them. Spread across notes, tabs and messages, that material stops being an asset — it cannot be found at the moment it is needed.",
        "approach": "We kept the system deliberately simple. A structured environment for capturing knowledge only works if the act of capturing is effortless, so usability drove the design, with scalability behind it so a workspace stays usable as it fills up.",
        "solution": "A digital platform for organising ideas, managing information and improving personal productivity. It provides a structured environment for capturing knowledge, tracking important content and maintaining information in a centralised workspace, so users stay organised and reach what they need efficiently.",
        "focus": ["User experience", "Scalability", "Practical everyday use"],
        "results": [],
        "technologies": [],
        "testimonial": None,
    },
    {
        "slug": "business-process-automation",
        "title": "Business Process Automation Platform",
        "client": "",
        "illustrative": False,
        "sector": "Business Automation",
        "year": "",
        "teaser": "Workflow automation that removes repetitive manual steps, centralises process management and gives teams visibility into how work actually flows.",
        "challenge": "Repetitive manual tasks and workflows that live in people's heads are a quiet tax on any organisation. They consume effort, slow processes down, and leave managers without a clear view of where work is stuck.",
        "approach": "We started from the workflows themselves rather than from a tool. Automating the repetitive steps and centralising process management reduces manual effort where it is heaviest, and improved process visibility gives teams what they need to keep improving after we leave.",
        "solution": "A workflow automation solution that streamlines business operations and improves process efficiency across teams. Organisations automate repetitive tasks, manage workflows and collaborate through a centralised system — reducing manual effort, increasing productivity and improving process visibility.",
        "focus": ["Scalability", "Reliability", "Operational excellence"],
        "results": [],
        "technologies": [],
        "testimonial": None,
    },
    {
        "slug": "elearning-skill-development",
        "title": "E-Learning & Skill Development Platform",
        "client": "",
        "illustrative": False,
        "sector": "Education",
        "year": "",
        "teaser": "An interactive learning environment for delivering training and skill development at scale, with progress tracking built in.",
        "challenge": "Organisations and institutions moving education online need more than a content library. Without an interactive environment and a way to track progress, learning delivery is hard to scale and harder still to evaluate.",
        "approach": "We designed for engagement rather than distribution. Learners need an environment that holds attention and shows them their own progress; institutions need delivery that scales and stays accessible. The platform was built to serve both at once.",
        "solution": "A comprehensive digital learning platform supporting online education, training and skill development. Users access educational content, track progress and learn in an interactive environment, enabling organisations and institutions to deliver effective digital education at scale.",
        "focus": ["Engagement", "Usability", "Learning outcomes"],
        "results": [],
        "technologies": [],
        "testimonial": None,
    },
    {
        "slug": "document-processing-automation",
        "title": "Document Processing & Automation Solution",
        "client": "",
        "illustrative": False,
        "sector": "Business Automation",
        "year": "",
        "teaser": "Document handling and information extraction automated end to end, cutting manual effort and turnaround time on document-driven processes.",
        "challenge": "Document-driven processes are where operational time disappears. Handling documents by hand and re-keying the information inside them is slow and error-prone, and it leaves the resulting data difficult to reach across the rest of the business.",
        "approach": "We targeted the extraction step, because that is where the manual effort concentrates. Processing documents efficiently and making the extracted information accessible turns a bottleneck into a pass-through — integrated into the surrounding workflow rather than sitting beside it.",
        "solution": "A business automation solution that simplifies document handling and information extraction workflows. Organisations process documents efficiently, reduce manual effort and improve data accessibility across operations, enabling faster turnaround times and enhanced operational productivity.",
        "focus": ["Accuracy", "Efficiency", "Seamless workflow integration"],
        "results": [],
        "technologies": [],
        "testimonial": None,
    },
    {
        "slug": "digital-learning-management",
        "title": "Digital Learning Management Platform",
        "client": "",
        "illustrative": False,
        "sector": "Education",
        "year": "",
        "teaser": "A learning management platform giving learners structured access to resources and progress tracking, and administrators the means to run programmes.",
        "challenge": "Training programmes and skill development initiatives stall when learners cannot easily find resources or see how far they have come, and when administrators have no structured way to run the programme behind them.",
        "approach": "We built for both sides of the platform. Learners get a structured digital environment that makes resources accessible and progress visible; administrators get the means to manage programmes — with accessibility and learning efficiency as the measures of whether the design works.",
        "solution": "A modern learning platform supporting online education, training programmes and skill development initiatives. Learners access educational resources, track their progress and engage with content in a structured digital environment, delivered as a scalable end-to-end solution for learners and administrators alike.",
        "focus": ["Usability", "Engagement", "Educational growth"],
        "results": [],
        "technologies": [],
        "testimonial": None,
    },
]

POSTS = [
    {
        "slug": "before-you-buy-ai",
        "title": "Before you buy AI, understand the problem",
        "category": "AI Strategy",
        "excerpt": "The most expensive words in enterprise technology are 'we should be doing something with AI.' Here's the discipline that separates value from theatre.",
        "author": "AADRIQUE Editorial",
        "date": "2026-05-18",
        "reading_time": 6,
        "content": [
            {"h": "Start with the P&L, not the model", "p": "Every AI initiative should trace to a line in the P&L: a cost to reduce, a revenue stream to grow, a risk to contain. If the trace isn't obvious, the project is a science experiment — which is fine, as long as it's budgeted as one. The failure mode we see most often is theatre: a chatbot launched because a board member asked about AI, measured by nothing, quietly retired within a year."},
            {"h": "The three questions that filter 80% of ideas", "p": "First: what decision or task does this change, and who performs it today? Second: what data does it need, and does that data exist in usable form? Third: what happens when it's wrong — and can the workflow absorb that? Most proposals fail at least one. That's not a reason for pessimism; it's a filter that concentrates budget on the ideas that survive."},
            {"h": "Pilot like you mean to ship", "p": "A pilot that runs on curated data, with no integration, evaluated by the team that built it, tells you almost nothing. Pilot on real data, inside the real workflow, judged by the people who will live with it. It costs slightly more and saves you from the far larger cost of scaling something that never worked."},
            {"h": "Where to start on Monday", "p": "Pick one process that is high-volume, rule-adjacent and painful — document intake, ticket triage, reconciliation. Measure its current cost honestly. Then evaluate whether AI, automation, or a simpler process fix moves that number. Sometimes the answer isn't AI at all. A partner who tells you that is worth keeping."},
        ],
    },
    {
        "slug": "transformation-roadmap-smes",
        "title": "The transformation roadmap most SMEs actually need",
        "category": "Digital Transformation",
        "excerpt": "Forget the 3-year programme. For most mid-size businesses, transformation is a sequence of 90-day wins that fund each other.",
        "author": "AADRIQUE Editorial",
        "date": "2026-04-22",
        "reading_time": 5,
        "content": [
            {"h": "The big-bang trap", "p": "Large transformation programmes borrow their shape from enterprises with enterprise budgets. For an SME, an 18-month programme with value arriving at the end is not a plan — it's a bet the balance sheet can't cover. The alternative isn't smaller ambition; it's smarter sequencing."},
            {"h": "Sequence by friction, not by fashion", "p": "The right first project is rarely the most exciting one. It's the process your team complains about weekly: the reconciliation that eats Fridays, the approvals that live in someone's inbox, the report that takes three days to assemble. These carry measurable cost, visible pain and quick payback — which builds the organisational trust every later phase depends on."},
            {"h": "90-day increments, compounding returns", "p": "Structure transformation as consecutive 90-day increments, each delivering working software and a measured saving. The savings from phase one are real budget for phase two. Momentum, not vision decks, is what carries change through an organisation."},
            {"h": "What to insist on from any partner", "p": "Working software every month. A number that moves every quarter. Knowledge transferred, not hoarded. And a partner willing to say 'that phase isn't worth doing' — because a roadmap with nothing removed from it was never really prioritised."},
        ],
    },
    {
        "slug": "data-readiness-unglamorous-half",
        "title": "Data readiness: the unglamorous half of every AI project",
        "category": "Data & Analytics",
        "excerpt": "Models are commodities. Your data pipelines aren't. Why the boring work decides whether the exciting work succeeds.",
        "author": "AADRIQUE Editorial",
        "date": "2026-03-15",
        "reading_time": 7,
        "content": [
            {"h": "The 70/30 rule nobody budgets for", "p": "In practice, 70% of an AI project's effort goes into data: locating it, cleaning it, agreeing what fields mean, building pipelines that don't silently break. Teams that budget as if the model is the work end up with beautiful demos on data that doesn't exist in production."},
            {"h": "Readiness is specific, not general", "p": "'Our data is a mess' is almost never uniformly true. Data readiness only matters relative to a use case. Your invoice data might be excellent while your CRM is chaos — which makes document automation viable today and churn prediction a next-year project. Assess readiness per use case and the roadmap writes itself."},
            {"h": "Definitions before dashboards", "p": "The most common analytics failure isn't technical: it's two departments computing 'revenue' differently and losing trust in every report. A metrics layer — agreed definitions, owned by named people, versioned like code — costs a fraction of a dashboard programme and determines whether anyone believes the dashboards."},
            {"h": "A pragmatic readiness checklist", "p": "For the use case in question: Can you locate all required data? Can you access it without a three-week ticket? Is it complete enough — not perfect, enough? Is there a defined owner when it breaks? Four yeses and you're ready to build. Fewer, and the first project is fixing that — which is still progress, just honest progress."},
        ],
    },
    {
        "slug": "build-vs-buy-2026",
        "title": "Build vs. buy in 2026: a decision framework",
        "category": "Technology Strategy",
        "excerpt": "AI-assisted development has changed the economics of custom software. The old defaults deserve re-examination.",
        "author": "AADRIQUE Editorial",
        "date": "2026-02-10",
        "reading_time": 6,
        "content": [
            {"h": "The economics moved", "p": "For two decades the default advice was 'buy unless it's your core differentiator' — because custom software was slow and expensive to build and worse to maintain. AI-assisted development has shifted that curve meaningfully. Systems that took nine months now take three. The advice needs updating, not discarding."},
            {"h": "Buy when the process is generic", "p": "Payroll, accounting, email, CRM for a standard sales motion: buy. These are solved problems where vendors amortise development across thousands of customers, and your process genuinely isn't special. The hidden cost of buying is workflow distortion — acceptable when your workflow is standard."},
            {"h": "Build when the workflow is the moat", "p": "If a process is how you win — your underwriting logic, your fulfilment orchestration, your client experience — forcing it into a vendor's assumptions taxes the very thing that differentiates you. That tax compounds annually. Custom systems here aren't an expense; they're margin defence."},
            {"h": "The 2026 middle path", "p": "The strongest pattern we see: buy commodity systems, then build the thin custom layer that connects them to how you actually operate — the integrations, automations and interfaces vendors will never ship. Small surface area, high leverage, and maintainable by a small team."},
        ],
    },
    {
        "slug": "cloud-cost-discipline",
        "title": "Cloud cost discipline as a product feature",
        "category": "Cloud & Engineering",
        "excerpt": "Cloud bills don't spike — they drift. Treating cost as an engineering metric, not a finance complaint, changes the trajectory.",
        "author": "AADRIQUE Editorial",
        "date": "2026-01-08",
        "reading_time": 5,
        "content": [
            {"h": "Drift, not spikes", "p": "Almost no company gets a shocking cloud bill overnight. They get 4% monthly drift: instances sized for a launch that never scaled down, storage nobody audits, dev environments running weekends. Eighteen months later the bill has doubled and no single decision caused it."},
            {"h": "Make cost visible where decisions happen", "p": "Finance sees the bill; engineers make the choices. Until cost per service appears in the same dashboards as latency and errors, engineers can't optimise what they can't see. Tag everything, attribute everything, and review cost in the same meeting as reliability."},
            {"h": "The boring 40%", "p": "Most savings need no architecture: rightsizing over-provisioned instances, deleting unattached storage, scheduling non-production environments, committing to reservations for stable workloads. Industry audits of unoptimised accounts routinely find 25–45% in this category alone. The remaining savings require design changes — worth it, but start with the free money."},
            {"h": "Discipline over heroics", "p": "A quarterly cost-cutting sprint is heroics; a monthly 30-minute review with clear ownership is discipline. Discipline wins. The goal isn't the minimum bill — it's a bill that grows slower than revenue, with every rupee traceable to something the business values."},
        ],
    },
]

FAQS = [
    {"category": "Working with AADRIQUE", "items": [
        {"q": "How do engagements usually start?", "a": "With a free consultation call, followed by a short paid discovery (1–3 weeks) that produces a concrete assessment and roadmap. You get standalone value from discovery even if we never build together."},
        {"q": "Do you work with companies outside India?", "a": "Yes. We serve a global client base with India-first delivery. Our teams overlap working hours with US, European and APAC time zones."},
        {"q": "What size of company do you work with?", "a": "From funded startups to enterprises and public institutions. The common thread is a real business problem and a leadership team serious about solving it."},
        {"q": "Can you work with our in-house team?", "a": "Preferably. Most engagements are collaborative — we augment your team, pair deliberately, and transfer knowledge so capability stays after we leave."},
    ]},
    {"category": "Engagements & pricing", "items": [
        {"q": "How do you price engagements?", "a": "Discovery phases are fixed-price. Delivery is phased with fixed scope per phase and re-approval gates — no open-ended time-and-materials drift."},
        {"q": "What's a typical engagement size?", "a": "Discovery engagements typically start from a few weeks of focused work; delivery phases range from 6-week builds to multi-quarter transformation programmes. We'll size honestly during the first call."},
        {"q": "Do you offer ongoing support after delivery?", "a": "Yes — support and evolution retainers with defined SLAs, or a structured handover to your team with documentation and training. Your choice."},
        {"q": "What if the assessment says we don't need AI?", "a": "Then we'll say so, in writing, with what we'd recommend instead. Our value is judgement — it would be worthless if it always concluded 'hire us to build AI.'"},
    ]},
    {"category": "Technology & delivery", "items": [
        {"q": "Who owns the intellectual property?", "a": "You do. Full IP transfer of code, designs and documentation is our standard contract position."},
        {"q": "How do you handle security and data privacy?", "a": "Security review is part of every build: encrypted data at rest and transit, least-privilege access, audit logs, and compliance alignment (DPDP, GDPR, HIPAA-adjacent controls) where your context requires it."},
        {"q": "Which technologies do you specialise in?", "a": "Modern, boring-by-choice stacks: React, Python/FastAPI, Node.js, PostgreSQL, MongoDB, and the three major clouds. For AI: the leading LLM providers, RAG architectures and evaluation tooling."},
        {"q": "How do you report progress?", "a": "Working software demos every sprint, a written progress note weekly, and metrics against the agreed success criteria. No status theatre."},
    ]},
]

TESTIMONIALS = [
    {"quote": "They asked harder questions about our business in week one than vendors we'd worked with for years.", "author": "CEO, healthcare network", "case_study": "healthcare-intake-automation"},
    {"quote": "The roadmap they gave us removed two projects we were about to fund. That honesty paid for the engagement by itself.", "author": "Managing Director, retail group", "case_study": "retail-demand-analytics"},
    {"quote": "Working software every two weeks, a number that moved every quarter. Exactly as promised.", "author": "VP Engineering, logistics provider", "case_study": "logistics-cloud-migration"},
]
