SEED_VERSION = 3

SERVICES = [
    {
        "slug": "ai-consulting",
        "title": "AI Consulting",
        "tagline": "Clarity before code.",
        "summary": "Independent, business-first advice on where AI genuinely creates value in your organisation — and where it doesn't.",
        "problem": "Most AI initiatives fail not because of the technology, but because they were never tied to a business problem worth solving. Boards feel pressure to 'do AI'; teams buy tools before defining outcomes.",
        "what_we_do": [
            "Assess your operations, data and workflows to find high-value AI opportunities",
            "Score each opportunity by business impact, feasibility and risk",
            "Design a pragmatic AI roadmap with clear owners, budgets and milestones",
            "Advise on build vs. buy, vendor selection and governance",
        ],
        "process": [
            {"step": "Discover", "desc": "Structured interviews and process mapping across functions to understand how your business actually runs."},
            {"step": "Assess", "desc": "Data readiness audit and opportunity scoring — impact, feasibility, cost and risk for every candidate use case."},
            {"step": "Recommend", "desc": "A prioritised roadmap with business cases, not a slide deck of buzzwords."},
            {"step": "Enable", "desc": "Pilot definition, vendor evaluation and governance frameworks so execution starts on solid ground."},
        ],
        "deliverables": ["AI opportunity assessment report", "Prioritised AI roadmap with business cases", "Data readiness audit", "Build vs. buy recommendations", "Governance and risk framework"],
        "tech_stack": ["OpenAI / Anthropic / Gemini", "Azure AI", "AWS Bedrock", "LangChain", "Vector databases", "MLOps tooling"],
        "faqs": [
            {"q": "Do we need clean data before engaging you?", "a": "No. Assessing data readiness is part of the engagement. We tell you exactly what is usable today and what needs work."},
            {"q": "Are you tied to specific AI vendors?", "a": "We are vendor-neutral. Recommendations are driven by your context, budget and constraints — not partnership commissions."},
        ],
    },
    {
        "slug": "ai-transformation",
        "title": "AI Transformation",
        "tagline": "From pilot to production.",
        "summary": "End-to-end delivery of AI systems that move from proof-of-concept into daily business operations — measured, governed and adopted.",
        "problem": "The industry is littered with pilots that never shipped. Moving AI into production requires engineering discipline, change management and measurement — not just a model.",
        "what_we_do": [
            "Build production-grade AI systems: copilots, document intelligence, forecasting, agents",
            "Integrate AI into existing workflows, ERPs and CRMs rather than bolting on new tools",
            "Establish evaluation, monitoring and human-in-the-loop guardrails",
            "Train teams and manage adoption so the system is actually used",
        ],
        "process": [
            {"step": "Frame", "desc": "Define the workflow, the metric it must move, and the guardrails it must respect."},
            {"step": "Prototype", "desc": "A working prototype on your real data within weeks — evaluated against agreed success criteria."},
            {"step": "Industrialise", "desc": "Production engineering: security, latency, cost controls, monitoring, fallback behaviour."},
            {"step": "Adopt", "desc": "Training, rollout, and measurement. Value is only real when the team uses it daily."},
        ],
        "deliverables": ["Production AI application", "Evaluation and monitoring suite", "Integration with existing systems", "Team training and playbooks", "Cost and performance dashboards"],
        "tech_stack": ["LLM APIs (GPT, Claude, Gemini)", "RAG pipelines", "Python / FastAPI", "Vector search", "Kubernetes", "Observability tooling"],
        "faqs": [
            {"q": "How long until we see something working?", "a": "Typically 3–6 weeks to a working prototype on your data, depending on data access and complexity."},
            {"q": "How do you handle data privacy?", "a": "We design for your compliance context — private deployments, data residency, redaction and audit trails where required."},
        ],
    },
    {
        "slug": "digital-transformation",
        "title": "Digital Transformation",
        "tagline": "Modernise what matters.",
        "summary": "Replacing manual processes and legacy systems with modern digital operations — sequenced by business value, not by technology fashion.",
        "problem": "Transformation programmes fail when they try to change everything at once. The result: budget overruns, change fatigue, and systems nobody adopted.",
        "what_we_do": [
            "Map current processes and identify the highest-friction, highest-value areas first",
            "Modernise legacy systems incrementally with minimal business disruption",
            "Digitise paper and spreadsheet workflows into auditable systems",
            "Build the internal capability to sustain change after we leave",
        ],
        "process": [
            {"step": "Baseline", "desc": "Process mapping and cost-of-current-state analysis. You can't improve what you haven't measured."},
            {"step": "Sequence", "desc": "A phased roadmap ordered by ROI and risk — quick wins fund the deeper work."},
            {"step": "Deliver", "desc": "Iterative delivery in 2–4 week increments with working software at every step."},
            {"step": "Embed", "desc": "Training, documentation and handover so improvements survive beyond the engagement."},
        ],
        "deliverables": ["Current-state assessment", "Phased transformation roadmap", "Modernised systems and workflows", "Change management support", "Capability handover"],
        "tech_stack": ["React / Node / Python", "PostgreSQL / MongoDB", "Cloud platforms (AWS, Azure, GCP)", "API-first integration", "Low-code where appropriate"],
        "faqs": [
            {"q": "Can you work alongside our existing IT team?", "a": "Yes — most engagements are collaborative. We augment your team and transfer knowledge deliberately."},
            {"q": "What if we've had a failed transformation before?", "a": "Common, and usually a sequencing problem. We start with a smaller scope that proves value fast and rebuilds trust."},
        ],
    },
    {
        "slug": "custom-software-development",
        "title": "Custom Software Development",
        "tagline": "Software shaped to your business.",
        "summary": "Bespoke systems built when off-the-shelf tools can't model how your business actually works.",
        "problem": "Generic SaaS forces your operations into someone else's assumptions. Workarounds multiply, data fragments, and the tool becomes the bottleneck.",
        "what_we_do": [
            "Design and build custom platforms, portals and internal tools",
            "Replace brittle spreadsheet-driven operations with real systems",
            "Integrate disconnected tools into a coherent architecture",
            "Own quality end-to-end: architecture, testing, security, deployment",
        ],
        "process": [
            {"step": "Specify", "desc": "Workshops to define the domain model, workflows and edge cases before a line of code."},
            {"step": "Architect", "desc": "A design that fits your scale and budget today with clean paths to grow."},
            {"step": "Build", "desc": "Agile delivery with demos every sprint and honest progress reporting."},
            {"step": "Operate", "desc": "Deployment, monitoring, SLAs and ongoing evolution as your business changes."},
        ],
        "deliverables": ["Production application", "Technical architecture documentation", "Automated test suite", "CI/CD pipeline", "Maintenance and support plan"],
        "tech_stack": ["React / TypeScript", "Python / FastAPI / Node.js", "PostgreSQL / MongoDB", "Docker / Kubernetes", "AWS / Azure / GCP"],
        "faqs": [
            {"q": "Who owns the code?", "a": "You do. Full IP transfer, documented codebases, no lock-in."},
            {"q": "How do you keep projects on budget?", "a": "Fixed-scope discovery first, then phased delivery with re-approval gates. No open-ended billing."},
        ],
    },
    {
        "slug": "web-applications",
        "title": "Web Applications",
        "tagline": "Fast, secure, built to scale.",
        "summary": "High-performance web platforms — customer portals, SaaS products, marketplaces and internal dashboards.",
        "problem": "Slow, insecure or unscalable web software silently costs revenue: abandoned carts, churned users, support overhead, security exposure.",
        "what_we_do": [
            "Build responsive, accessible web applications with modern frameworks",
            "Engineer for performance: sub-second loads, efficient APIs, smart caching",
            "Bake in security, monitoring and analytics from day one",
            "Design information architecture that scales with your product roadmap",
        ],
        "process": [
            {"step": "Define", "desc": "User journeys, data model and success metrics agreed before design."},
            {"step": "Design", "desc": "Wireframes to high-fidelity UI with your brand system."},
            {"step": "Engineer", "desc": "Component-driven development, automated testing, staged environments."},
            {"step": "Launch", "desc": "Performance hardening, SEO, analytics and a measured rollout."},
        ],
        "deliverables": ["Production web application", "Design system and component library", "API layer and documentation", "Analytics and monitoring setup", "SEO foundation"],
        "tech_stack": ["React / Next.js", "FastAPI / Node.js", "PostgreSQL / MongoDB / Redis", "Tailwind CSS", "Vercel / AWS"],
        "faqs": [
            {"q": "Can you take over an existing application?", "a": "Yes. We run a technical audit first, stabilise what's critical, then improve incrementally."},
            {"q": "Do you handle hosting and maintenance?", "a": "We can own the full lifecycle or hand over to your team with complete documentation — your choice."},
        ],
    },
    {
        "slug": "mobile-applications",
        "title": "Mobile Applications",
        "tagline": "Your business, in their pocket.",
        "summary": "iOS and Android applications for customers and field teams — native quality with pragmatic cross-platform engineering.",
        "problem": "A poor mobile experience is a daily reminder to churn. And building two native apps badly costs more than building one cross-platform app well.",
        "what_we_do": [
            "Build cross-platform apps with React Native / Flutter where it fits, native where it matters",
            "Design offline-first field and operations apps for real-world conditions",
            "Integrate payments, notifications, maps and device capabilities",
            "Manage store submission, releases and crash monitoring",
        ],
        "process": [
            {"step": "Scope", "desc": "Platform strategy, feature prioritisation, and an honest cross-platform vs. native recommendation."},
            {"step": "Prototype", "desc": "Clickable prototype validated with real users before full build."},
            {"step": "Build", "desc": "Sprint-based delivery with TestFlight / Play beta builds throughout."},
            {"step": "Ship", "desc": "Store approval, phased rollout, analytics and iteration."},
        ],
        "deliverables": ["Published iOS and Android apps", "Backend APIs and admin panel", "Push notification infrastructure", "Crash and analytics monitoring", "Release playbook"],
        "tech_stack": ["React Native / Flutter", "Swift / Kotlin (native modules)", "Firebase", "FastAPI backends", "App Store / Play Console"],
        "faqs": [
            {"q": "Cross-platform or native?", "a": "For most business apps, cross-platform delivers 90% of native quality at 60% of the cost. We'll tell you honestly if your case is the exception."},
            {"q": "Do you handle app store approval?", "a": "Yes — including compliance review, store assets and rejection handling."},
        ],
    },
    {
        "slug": "ui-ux-design",
        "title": "UI/UX Design",
        "tagline": "Design that earns trust.",
        "summary": "Research-driven product design — from user flows to polished interfaces and design systems your team can build on.",
        "problem": "Ugly software gets tolerated; confusing software gets abandoned. Poor UX shows up as support tickets, training costs and lost deals.",
        "what_we_do": [
            "Run user research and usability audits on existing products",
            "Design end-to-end flows, wireframes and high-fidelity interfaces",
            "Build token-driven design systems for consistency at scale",
            "Prototype and test before engineering spends a rupee",
        ],
        "process": [
            {"step": "Research", "desc": "User interviews, analytics review and heuristic evaluation."},
            {"step": "Structure", "desc": "Information architecture and user flows that remove friction."},
            {"step": "Design", "desc": "High-fidelity UI with your brand, tested with real users."},
            {"step": "Systemise", "desc": "A documented design system so quality survives handover."},
        ],
        "deliverables": ["UX audit report", "User flows and wireframes", "High-fidelity UI designs", "Interactive prototypes", "Design system and tokens"],
        "tech_stack": ["Figma", "Design tokens", "Framer prototyping", "Accessibility tooling (WCAG 2.1)", "Usability testing platforms"],
        "faqs": [
            {"q": "Can you redesign without breaking what users know?", "a": "Yes — evolutionary redesign is our default. We fix friction without discarding learned behaviour."},
            {"q": "Do you hand off to our developers?", "a": "We deliver developer-ready specs, tokens and a walkthrough. We can also pair with your team during build."},
        ],
    },
    {
        "slug": "cloud-solutions",
        "title": "Cloud Solutions",
        "tagline": "Infrastructure without drama.",
        "summary": "Cloud migration, architecture and cost optimisation on AWS, Azure and GCP — reliable, secure and financially disciplined.",
        "problem": "Cloud bills grow silently. Legacy servers create risk. And migrations done badly cause the outages they were meant to prevent.",
        "what_we_do": [
            "Plan and execute zero-downtime cloud migrations",
            "Design secure, scalable architectures sized to actual demand",
            "Cut cloud spend through rightsizing, reservations and architectural fixes",
            "Set up infrastructure-as-code, CI/CD and disaster recovery",
        ],
        "process": [
            {"step": "Audit", "desc": "Current infrastructure, dependencies, risk and cost baseline."},
            {"step": "Design", "desc": "Target architecture with security, compliance and cost modelling."},
            {"step": "Migrate", "desc": "Phased, rehearsed cutovers with rollback plans. No big-bang weekends."},
            {"step": "Optimise", "desc": "Continuous cost and performance tuning with monthly reporting."},
        ],
        "deliverables": ["Cloud architecture design", "Migration execution", "Infrastructure-as-code (Terraform)", "Cost optimisation report", "DR and backup strategy"],
        "tech_stack": ["AWS / Azure / GCP", "Terraform / Pulumi", "Kubernetes / Docker", "GitHub Actions / GitLab CI", "Datadog / Grafana"],
        "faqs": [
            {"q": "Can you reduce our existing cloud bill?", "a": "Typically 25–45% on unoptimised accounts. We audit first and quantify savings before you commit. [Placeholder figure]"},
            {"q": "Which cloud should we choose?", "a": "The one that fits your workloads, team skills and existing contracts. We're certified across all three majors and have no resale incentive."},
        ],
    },
    {
        "slug": "data-analytics",
        "title": "Data Analytics",
        "tagline": "Decisions, not dashboards.",
        "summary": "Data pipelines, warehouses and analytics that turn scattered operational data into decisions leadership can act on.",
        "problem": "Most organisations are data-rich and insight-poor. Reports take days, numbers don't reconcile, and decisions default to gut feel.",
        "what_we_do": [
            "Consolidate scattered data sources into a governed warehouse",
            "Build automated reporting and self-serve dashboards",
            "Develop forecasting and anomaly detection models",
            "Establish data quality, definitions and ownership",
        ],
        "process": [
            {"step": "Map", "desc": "Inventory data sources, owners and the decisions each metric should drive."},
            {"step": "Pipeline", "desc": "Reliable ELT into a single warehouse with tested transformations."},
            {"step": "Model", "desc": "Metrics layer with agreed definitions — one version of the truth."},
            {"step": "Activate", "desc": "Dashboards, alerts and forecasts embedded into weekly operating rhythm."},
        ],
        "deliverables": ["Data warehouse and pipelines", "Metrics layer and documentation", "Executive and operational dashboards", "Forecasting models", "Data governance framework"],
        "tech_stack": ["BigQuery / Snowflake / ClickHouse", "dbt", "Airflow / Dagster", "Metabase / Power BI / Looker", "Python / SQL"],
        "faqs": [
            {"q": "Our data is a mess. Where do we start?", "a": "With the three decisions that matter most to leadership. We build backwards from those, not forwards from every table you own."},
            {"q": "How long to a first dashboard?", "a": "A trustworthy first dashboard on consolidated data typically lands in 4–6 weeks."},
        ],
    },
    {
        "slug": "automation",
        "title": "Automation",
        "tagline": "Remove the repetitive.",
        "summary": "Workflow and process automation that eliminates manual, error-prone work — from document processing to cross-system orchestration.",
        "problem": "Skilled people spend hours re-typing data between systems, chasing approvals and reconciling spreadsheets. That time has a cost — and a better use.",
        "what_we_do": [
            "Automate document-heavy workflows with intelligent extraction",
            "Orchestrate cross-system processes: approvals, onboarding, reconciliation",
            "Deploy RPA and API-based automation where each fits best",
            "Measure hours saved and error rates so ROI is visible",
        ],
        "process": [
            {"step": "Observe", "desc": "Shadow the actual process — not the documented one — to find real friction."},
            {"step": "Quantify", "desc": "Hours, error rates and cost per process. Automation targets ranked by payback."},
            {"step": "Automate", "desc": "Build with humans-in-the-loop for exceptions, not blind straight-through processing."},
            {"step": "Scale", "desc": "Extend to adjacent processes once the first automation proves its numbers."},
        ],
        "deliverables": ["Process automation implementation", "Exception handling workflows", "ROI measurement dashboard", "Runbooks and training", "Automation roadmap"],
        "tech_stack": ["Python", "n8n / Zapier / Make", "OCR + LLM extraction", "REST / webhook integration", "RPA platforms"],
        "faqs": [
            {"q": "Will automation replace our staff?", "a": "In our engagements it redirects them. The business case is usually capacity and accuracy, not headcount."},
            {"q": "What's a typical payback period?", "a": "Well-chosen automations pay back in 3–9 months. We won't build ones that don't. [Placeholder figure]"},
        ],
    },
    {
        "slug": "technology-consulting",
        "title": "Technology Consulting",
        "tagline": "A CTO's judgement, on demand.",
        "summary": "Independent technology strategy, architecture review and vendor guidance for leadership teams making high-stakes decisions.",
        "problem": "Technology decisions made without independent expertise become expensive to reverse: wrong platforms, bad contracts, unscalable architectures.",
        "what_we_do": [
            "Advise on technology strategy, budgets and team structure",
            "Review architectures and codebases before you buy, build or scale",
            "Support vendor selection, RFPs and contract negotiation",
            "Provide fractional CTO leadership for growing organisations",
        ],
        "process": [
            {"step": "Context", "desc": "Business goals, constraints and the decision on the table."},
            {"step": "Investigate", "desc": "Technical due diligence: systems, vendors, teams, contracts."},
            {"step": "Advise", "desc": "Clear, written recommendations with trade-offs made explicit."},
            {"step": "Support", "desc": "Ongoing counsel through execution — not advice and exit."},
        ],
        "deliverables": ["Technology strategy document", "Architecture / code audit report", "Vendor evaluation matrix", "Budget and roadmap review", "Fractional CTO engagement"],
        "tech_stack": ["Architecture review frameworks", "Cloud cost analysis", "Security posture assessment", "Due diligence tooling", "Engineering metrics"],
        "faqs": [
            {"q": "When does fractional CTO make sense?", "a": "When technology decisions outpace in-house expertise but a full-time CTO isn't justified yet — commonly ₹50L–₹5Cr technology budgets."},
            {"q": "Can you audit a vendor's proposal?", "a": "Yes — technical and commercial review of proposals, architectures and contracts is one of our most requested services."},
        ],
    },
]

INDUSTRIES = [
    {
        "slug": "healthcare",
        "name": "Healthcare",
        "headline": "Care delivery, minus the paperwork.",
        "overview": "Hospitals, clinics and health networks run on processes that were never designed for scale. We digitise patient journeys, automate administration and make clinical data usable — within compliance boundaries.",
        "challenges": ["Manual patient intake, records and claims processing", "Fragmented systems across departments and locations", "Compliance and data privacy obligations", "Staff time consumed by administration instead of care"],
        "solutions": ["Patient intake and appointment automation", "Claims triage and document intelligence", "Unified dashboards across facilities", "Secure, compliant data platforms"],
        "outcomes": ["Faster patient throughput", "Lower administrative cost per case", "Audit-ready compliance posture"],
        "related_case_study": "healthcare-intake-automation",
    },
    {
        "slug": "retail-ecommerce",
        "name": "Retail & E-commerce",
        "headline": "Every store, every SKU, one picture.",
        "overview": "Retail margins are won in inventory, pricing and customer experience. We build the data and automation backbone that lets retailers act on demand signals instead of reacting to stockouts.",
        "challenges": ["Stockouts and overstock from gut-feel forecasting", "Disconnected online and offline channels", "Margin erosion hidden in scattered data", "Manual reconciliation across POS, ERP and marketplaces"],
        "solutions": ["Demand forecasting and inventory intelligence", "Omnichannel data consolidation", "Pricing and promotion analytics", "Order and returns automation"],
        "outcomes": ["Fewer stockouts, leaner inventory", "Margin visibility by store and SKU", "Hours of reconciliation removed weekly"],
        "related_case_study": "retail-demand-analytics",
    },
    {
        "slug": "education",
        "name": "Education",
        "headline": "Institutions built for modern learners.",
        "overview": "Universities, school groups and ed-tech ventures need digital platforms that serve students at scale — admissions to alumni — without an army of administrators.",
        "challenges": ["Paper-driven admissions and administration", "Poor visibility into student progress and risk", "Legacy portals students avoid using", "Faculty time lost to repetitive coordination"],
        "solutions": ["Digital learning and administration platforms", "Student analytics and early-warning systems", "Admissions and fee workflow automation", "Modern student-facing portals and apps"],
        "outcomes": ["Higher completion and engagement", "Faster admissions cycles", "Administration cost per student down"],
        "related_case_study": "education-learning-platform",
    },
    {
        "slug": "financial-services",
        "name": "Financial Services",
        "headline": "Trust, speed and compliance — together.",
        "overview": "Lenders, insurers and fintechs compete on speed of decision and quality of risk. We build the data pipelines, automation and secure platforms that make both possible.",
        "challenges": ["Slow, manual underwriting and KYC processes", "Regulatory reporting consuming analyst time", "Legacy core systems limiting product launches", "Fraud and risk signals scattered across systems"],
        "solutions": ["Document intelligence for KYC and underwriting", "Automated regulatory reporting pipelines", "API layers over legacy cores", "Risk analytics and monitoring"],
        "outcomes": ["Decision times cut from days to hours", "Reporting produced automatically", "New products launched without core replacement"],
        "related_case_study": None,
    },
    {
        "slug": "manufacturing-logistics",
        "name": "Manufacturing & Logistics",
        "headline": "The physical world, digitally visible.",
        "overview": "Plants, fleets and warehouses generate enormous operational data that rarely reaches decision-makers in time. We connect operations to systems that see problems before they become losses.",
        "challenges": ["No real-time visibility into production or fleet status", "Downtime discovered after the cost is incurred", "Manual planning across procurement, production and dispatch", "Ageing on-premise systems nearing end of life"],
        "solutions": ["Operations dashboards and alerting", "Predictive maintenance analytics", "Planning and dispatch automation", "Cloud migration of legacy systems"],
        "outcomes": ["Downtime caught earlier, cost avoided", "Planning cycles compressed", "Infrastructure cost reduced"],
        "related_case_study": "logistics-cloud-migration",
    },
    {
        "slug": "government-public-sector",
        "name": "Government & Public Sector",
        "headline": "Citizen services that actually serve.",
        "overview": "Public institutions carry the highest bar for accessibility, transparency and scale. We build citizen-facing services and internal systems that meet it — pragmatically and accountably.",
        "challenges": ["Paper-based citizen services with long queues", "Data locked in departmental silos", "Procurement and compliance complexity", "Accessibility obligations often unmet"],
        "solutions": ["Digital citizen service portals", "Inter-department data platforms", "Workflow digitisation with audit trails", "WCAG-compliant accessible interfaces"],
        "outcomes": ["Service turnaround times reduced", "Full auditability of every request", "Accessible to every citizen"],
        "related_case_study": None,
    },
]

CASE_STUDIES = [
    {
        "slug": "healthcare-intake-automation",
        "title": "Automating patient intake for a multi-specialty hospital network",
        "client": "[Placeholder] Multi-specialty hospital network, India",
        "sector": "Healthcare",
        "year": "2025",
        "teaser": "Manual intake and claims triage were consuming 40+ staff-hours daily. We rebuilt the journey around document intelligence and workflow automation.",
        "challenge": "Patient registration, insurance verification and claims triage ran on paper forms and re-keyed data across three systems. Errors caused claim rejections; queues damaged patient experience; staff overtime grew every quarter.",
        "approach": "We shadowed intake teams across two facilities for a week before proposing anything. The bottleneck wasn't staff speed — it was triple data entry and unreadable referral documents. We designed an intake platform around document extraction with human review only for exceptions.",
        "solution": "A digital intake system with OCR + LLM extraction of referral and insurance documents, automatic eligibility checks, and a triage queue that routes exceptions to staff. Integrated with the existing HIS via APIs rather than replacing it.",
        "results": [
            {"metric": "-62%", "label": "intake processing time"},
            {"metric": "3.4x", "label": "faster claims triage"},
            {"metric": "₹2.1 Cr", "label": "annual operating saving"},
        ],
        "technologies": ["Python / FastAPI", "OCR + LLM extraction", "React", "MongoDB", "HIS API integration"],
        "testimonial": {"quote": "[Placeholder] The team refused to write code until they understood our wards. That discipline is why this system is actually used.", "author": "[Placeholder] Chief Operating Officer"},
    },
    {
        "slug": "retail-demand-analytics",
        "title": "Demand forecasting for an omnichannel retail chain",
        "client": "[Placeholder] Omnichannel retail chain, 140+ stores",
        "sector": "Retail & E-commerce",
        "year": "2025",
        "teaser": "Store managers ordered on instinct; the company paid in stockouts and dead stock. We built a forecasting platform they actually trust.",
        "challenge": "Fourteen data sources, no single view of inventory, and forecasting done per-store in spreadsheets. Fast-moving SKUs stocked out while slow movers accumulated. Working capital was locked in the wrong shelves.",
        "approach": "Before modelling anything we consolidated POS, warehouse and marketplace data into a governed warehouse and agreed metric definitions with finance. Forecast accuracy was benchmarked openly against manager intuition for one full quarter.",
        "solution": "An ELT pipeline into a cloud warehouse, a demand forecasting model at SKU-store level with seasonality and promotion effects, and a replenishment dashboard with recommended orders that managers approve — keeping humans in charge.",
        "results": [
            {"metric": "-28%", "label": "stockout events"},
            {"metric": "+12%", "label": "gross margin on covered SKUs"},
            {"metric": "9 wks", "label": "from kickoff to first rollout"},
        ],
        "technologies": ["BigQuery", "dbt", "Python forecasting", "Metabase", "POS / ERP integration"],
        "testimonial": {"quote": "[Placeholder] They benchmarked their model against our managers publicly. It won — and that's why adoption was never a fight.", "author": "[Placeholder] Head of Supply Chain"},
    },
    {
        "slug": "education-learning-platform",
        "title": "A digital learning platform for a private university group",
        "client": "[Placeholder] Private university group, 3 campuses",
        "sector": "Education",
        "year": "2024",
        "teaser": "Legacy portals students avoided, admissions on paper, and no view of learner risk. We delivered a platform 40,000 students actually use.",
        "challenge": "Three campuses ran separate legacy portals with sub-50% student adoption. Admissions took weeks of manual verification. Faculty had no early signal on students at risk of dropping out.",
        "approach": "We interviewed students, faculty and admissions staff before writing requirements — the existing portal's failure was UX, not features. The platform was rebuilt mobile-first around the five journeys students perform weekly.",
        "solution": "A unified learning and administration platform: mobile-first student portal, digitised admissions with document verification workflows, faculty dashboards, and an early-warning model flagging disengagement from attendance and submission patterns.",
        "results": [
            {"metric": "40k", "label": "students onboarded"},
            {"metric": "+31%", "label": "course completion improvement"},
            {"metric": "99.95%", "label": "platform uptime"},
        ],
        "technologies": ["React / React Native", "FastAPI", "PostgreSQL", "Redis", "AWS"],
        "testimonial": {"quote": "[Placeholder] For the first time, our students prefer the official platform to WhatsApp groups.", "author": "[Placeholder] Dean of Academics"},
    },
    {
        "slug": "logistics-cloud-migration",
        "title": "Zero-downtime cloud migration for a national logistics provider",
        "client": "[Placeholder] National logistics provider",
        "sector": "Manufacturing & Logistics",
        "year": "2024",
        "teaser": "End-of-life servers, quarterly deployments, and rising infrastructure risk. We migrated the core platform to cloud without a minute of downtime.",
        "challenge": "The tracking and dispatch platform ran on ageing on-premise servers with no failover. Deployments happened quarterly over risky weekends. Hardware end-of-life created an unavoidable deadline.",
        "approach": "Big-bang migration was ruled out on day one. We containerised services incrementally, ran cloud and on-premise in parallel with traffic mirroring, and rehearsed every cutover in staging before touching production.",
        "solution": "Phased migration to AWS with Kubernetes, infrastructure-as-code for every environment, CI/CD replacing manual deployments, and observability dashboards the operations team never had before.",
        "results": [
            {"metric": "-44%", "label": "infrastructure cost"},
            {"metric": "Weekly", "label": "deployments, from quarterly"},
            {"metric": "0 min", "label": "downtime during cutover"},
        ],
        "technologies": ["AWS", "Kubernetes", "Terraform", "GitHub Actions", "Grafana"],
        "testimonial": {"quote": "[Placeholder] Every cutover was rehearsed until it was boring. Exactly what you want from a migration.", "author": "[Placeholder] VP of Engineering"},
    },
]

POSTS = [
    {
        "slug": "before-you-buy-ai",
        "title": "Before you buy AI, understand the problem",
        "category": "AI Strategy",
        "excerpt": "The most expensive words in enterprise technology are 'we should be doing something with AI.' Here's the discipline that separates value from theatre.",
        "author": "AADRIQUE Editorial",
        "date": "2026-05-18",
        "reading_time": 6,
        "content": [
            {"h": "Start with the P&L, not the model", "p": "Every AI initiative should trace to a line in the P&L: a cost to reduce, a revenue stream to grow, a risk to contain. If the trace isn't obvious, the project is a science experiment — which is fine, as long as it's budgeted as one. The failure mode we see most often is theatre: a chatbot launched because a board member asked about AI, measured by nothing, quietly retired within a year."},
            {"h": "The three questions that filter 80% of ideas", "p": "First: what decision or task does this change, and who performs it today? Second: what data does it need, and does that data exist in usable form? Third: what happens when it's wrong — and can the workflow absorb that? Most proposals fail at least one. That's not a reason for pessimism; it's a filter that concentrates budget on the ideas that survive."},
            {"h": "Pilot like you mean to ship", "p": "A pilot that runs on curated data, with no integration, evaluated by the team that built it, tells you almost nothing. Pilot on real data, inside the real workflow, judged by the people who will live with it. It costs slightly more and saves you from the far larger cost of scaling something that never worked."},
            {"h": "Where to start on Monday", "p": "Pick one process that is high-volume, rule-adjacent and painful — document intake, ticket triage, reconciliation. Measure its current cost honestly. Then evaluate whether AI, automation, or a simpler process fix moves that number. Sometimes the answer isn't AI at all. A partner who tells you that is worth keeping."},
        ],
    },
    {
        "slug": "transformation-roadmap-smes",
        "title": "The transformation roadmap most SMEs actually need",
        "category": "Digital Transformation",
        "excerpt": "Forget the 3-year programme. For most mid-size businesses, transformation is a sequence of 90-day wins that fund each other.",
        "author": "AADRIQUE Editorial",
        "date": "2026-04-22",
        "reading_time": 5,
        "content": [
            {"h": "The big-bang trap", "p": "Large transformation programmes borrow their shape from enterprises with enterprise budgets. For an SME, an 18-month programme with value arriving at the end is not a plan — it's a bet the balance sheet can't cover. The alternative isn't smaller ambition; it's smarter sequencing."},
            {"h": "Sequence by friction, not by fashion", "p": "The right first project is rarely the most exciting one. It's the process your team complains about weekly: the reconciliation that eats Fridays, the approvals that live in someone's inbox, the report that takes three days to assemble. These carry measurable cost, visible pain and quick payback — which builds the organisational trust every later phase depends on."},
            {"h": "90-day increments, compounding returns", "p": "Structure transformation as consecutive 90-day increments, each delivering working software and a measured saving. The savings from phase one are real budget for phase two. Momentum, not vision decks, is what carries change through an organisation."},
            {"h": "What to insist on from any partner", "p": "Working software every month. A number that moves every quarter. Knowledge transferred, not hoarded. And a partner willing to say 'that phase isn't worth doing' — because a roadmap with nothing removed from it was never really prioritised."},
        ],
    },
    {
        "slug": "data-readiness-unglamorous-half",
        "title": "Data readiness: the unglamorous half of every AI project",
        "category": "Data & Analytics",
        "excerpt": "Models are commodities. Your data pipelines aren't. Why the boring work decides whether the exciting work succeeds.",
        "author": "AADRIQUE Editorial",
        "date": "2026-03-15",
        "reading_time": 7,
        "content": [
            {"h": "The 70/30 rule nobody budgets for", "p": "In practice, 70% of an AI project's effort goes into data: locating it, cleaning it, agreeing what fields mean, building pipelines that don't silently break. Teams that budget as if the model is the work end up with beautiful demos on data that doesn't exist in production."},
            {"h": "Readiness is specific, not general", "p": "'Our data is a mess' is almost never uniformly true. Data readiness only matters relative to a use case. Your invoice data might be excellent while your CRM is chaos — which makes document automation viable today and churn prediction a next-year project. Assess readiness per use case and the roadmap writes itself."},
            {"h": "Definitions before dashboards", "p": "The most common analytics failure isn't technical: it's two departments computing 'revenue' differently and losing trust in every report. A metrics layer — agreed definitions, owned by named people, versioned like code — costs a fraction of a dashboard programme and determines whether anyone believes the dashboards."},
            {"h": "A pragmatic readiness checklist", "p": "For the use case in question: Can you locate all required data? Can you access it without a three-week ticket? Is it complete enough — not perfect, enough? Is there a defined owner when it breaks? Four yeses and you're ready to build. Fewer, and the first project is fixing that — which is still progress, just honest progress."},
        ],
    },
    {
        "slug": "build-vs-buy-2026",
        "title": "Build vs. buy in 2026: a decision framework",
        "category": "Technology Strategy",
        "excerpt": "AI-assisted development has changed the economics of custom software. The old defaults deserve re-examination.",
        "author": "AADRIQUE Editorial",
        "date": "2026-02-10",
        "reading_time": 6,
        "content": [
            {"h": "The economics moved", "p": "For two decades the default advice was 'buy unless it's your core differentiator' — because custom software was slow and expensive to build and worse to maintain. AI-assisted development has shifted that curve meaningfully. Systems that took nine months now take three. The advice needs updating, not discarding."},
            {"h": "Buy when the process is generic", "p": "Payroll, accounting, email, CRM for a standard sales motion: buy. These are solved problems where vendors amortise development across thousands of customers, and your process genuinely isn't special. The hidden cost of buying is workflow distortion — acceptable when your workflow is standard."},
            {"h": "Build when the workflow is the moat", "p": "If a process is how you win — your underwriting logic, your fulfilment orchestration, your client experience — forcing it into a vendor's assumptions taxes the very thing that differentiates you. That tax compounds annually. Custom systems here aren't an expense; they're margin defence."},
            {"h": "The 2026 middle path", "p": "The strongest pattern we see: buy commodity systems, then build the thin custom layer that connects them to how you actually operate — the integrations, automations and interfaces vendors will never ship. Small surface area, high leverage, and maintainable by a small team."},
        ],
    },
    {
        "slug": "cloud-cost-discipline",
        "title": "Cloud cost discipline as a product feature",
        "category": "Cloud & Engineering",
        "excerpt": "Cloud bills don't spike — they drift. Treating cost as an engineering metric, not a finance complaint, changes the trajectory.",
        "author": "AADRIQUE Editorial",
        "date": "2026-01-08",
        "reading_time": 5,
        "content": [
            {"h": "Drift, not spikes", "p": "Almost no company gets a shocking cloud bill overnight. They get 4% monthly drift: instances sized for a launch that never scaled down, storage nobody audits, dev environments running weekends. Eighteen months later the bill has doubled and no single decision caused it."},
            {"h": "Make cost visible where decisions happen", "p": "Finance sees the bill; engineers make the choices. Until cost per service appears in the same dashboards as latency and errors, engineers can't optimise what they can't see. Tag everything, attribute everything, and review cost in the same meeting as reliability."},
            {"h": "The boring 40%", "p": "Most savings need no architecture: rightsizing over-provisioned instances, deleting unattached storage, scheduling non-production environments, committing to reservations for stable workloads. On unoptimised accounts this routinely finds 25–45%. [Placeholder figure] The remaining savings require design changes — worth it, but start with the free money."},
            {"h": "Discipline over heroics", "p": "A quarterly cost-cutting sprint is heroics; a monthly 30-minute review with clear ownership is discipline. Discipline wins. The goal isn't the minimum bill — it's a bill that grows slower than revenue, with every rupee traceable to something the business values."},
        ],
    },
]

FAQS = [
    {"category": "Working with AADRIQUE", "items": [
        {"q": "How do engagements usually start?", "a": "With a free consultation call, followed by a short paid discovery (1–3 weeks) that produces a concrete assessment and roadmap. You get standalone value from discovery even if we never build together."},
        {"q": "Do you work with companies outside India?", "a": "Yes. We serve a global client base with India-first delivery. Our teams overlap working hours with US, European and APAC time zones."},
        {"q": "What size of company do you work with?", "a": "From funded startups to enterprises and public institutions. The common thread is a real business problem and a leadership team serious about solving it."},
        {"q": "Can you work with our in-house team?", "a": "Preferably. Most engagements are collaborative — we augment your team, pair deliberately, and transfer knowledge so capability stays after we leave."},
    ]},
    {"category": "Engagements & pricing", "items": [
        {"q": "How do you price engagements?", "a": "Discovery phases are fixed-price. Delivery is phased with fixed scope per phase and re-approval gates — no open-ended time-and-materials drift."},
        {"q": "What's a typical engagement size?", "a": "Discovery engagements typically start from a few weeks of focused work; delivery phases range from 6-week builds to multi-quarter transformation programmes. We'll size honestly during the first call."},
        {"q": "Do you offer ongoing support after delivery?", "a": "Yes — support and evolution retainers with defined SLAs, or a structured handover to your team with documentation and training. Your choice."},
        {"q": "What if the assessment says we don't need AI?", "a": "Then we'll say so, in writing, with what we'd recommend instead. Our value is judgement — it would be worthless if it always concluded 'hire us to build AI.'"},
    ]},
    {"category": "Technology & delivery", "items": [
        {"q": "Who owns the intellectual property?", "a": "You do. Full IP transfer of code, designs and documentation is our standard contract position."},
        {"q": "How do you handle security and data privacy?", "a": "Security review is part of every build: encrypted data at rest and transit, least-privilege access, audit logs, and compliance alignment (DPDP, GDPR, HIPAA-adjacent controls) where your context requires it."},
        {"q": "Which technologies do you specialise in?", "a": "Modern, boring-by-choice stacks: React, Python/FastAPI, Node.js, PostgreSQL, MongoDB, and the three major clouds. For AI: the leading LLM providers, RAG architectures and evaluation tooling."},
        {"q": "How do you report progress?", "a": "Working software demos every sprint, a written progress note weekly, and metrics against the agreed success criteria. No status theatre."},
    ]},
]

TESTIMONIALS = [
    {"quote": "[Placeholder] They asked harder questions about our business in week one than vendors we'd worked with for years.", "author": "[Placeholder] CEO, healthcare network", "case_study": "healthcare-intake-automation"},
    {"quote": "[Placeholder] The roadmap they gave us removed two projects we were about to fund. That honesty paid for the engagement by itself.", "author": "[Placeholder] Managing Director, retail group", "case_study": "retail-demand-analytics"},
    {"quote": "[Placeholder] Working software every two weeks, a number that moved every quarter. Exactly as promised.", "author": "[Placeholder] VP Engineering, logistics provider", "case_study": "logistics-cloud-migration"},
]
